### ISSUE TITLE
Function issue after selecting all at bottom of mobile page

### ISSUE THREAD

**Issue by dmkravets** [8bitgentleman/roam-depot-mobile-bottombar#3]
I think this image will explain it all. But suffice to say, when I highlight a word at the bottom of a page, two popups come up, one of which gets in the way of the mobile bottombar popup, as illustrated here:
![Roam example](https://user-images.githubusercontent.com/16931277/188030363-703ebd5b-d884-4bd9-8bcf-2530f6ce55cd.png)
thanks

**Comment by 8bitgentleman** [comment]
I believe that cut/copy popup is part of iOS, nothing I can do about its placement unfortunately. Only thing you can do is scroll down so the block isn't so low on the page

**Comment by 8bitgentleman** [comment]
I assume even the native roam bottom bar would be covered with that popup as well

**Comment by dmkravets** [comment]
Points well taken @8bitgentleman 
On the feature request side, if you could add a button to **delete a block and all of its content**, that would make this extension even more spectacular! Thanks for your work on this! This extension is something that I have been craving since Roam released its mobile app.

**Comment by 8bitgentleman** [comment]
That's a great idea,[I just submitted a pr to add it! ](https://github.com/Roam-Research/roam-depot/pull/168) Should be merged soon
